-- =============================================================================
-- FILE: 01_schema.sql
-- PROJECT: E-Commerce Ad Campaign Analytics
-- AUTHOR: Sahil Rozera
-- DESCRIPTION: Creates all tables for the Olist e-commerce dataset +
--              simulated ad campaign data. Run this first before loading data.
-- =============================================================================


-- =============================================================================
-- SECTION 1: RAW TABLES (mirrors Olist CSV structure)
-- =============================================================================

DROP TABLE IF EXISTS raw_orders CASCADE;
CREATE TABLE raw_orders (
    order_id                        VARCHAR(50) PRIMARY KEY,
    customer_id                     VARCHAR(50),
    order_status                    VARCHAR(20),
    order_purchase_timestamp        TIMESTAMP,
    order_approved_at               TIMESTAMP,
    order_delivered_carrier_date    TIMESTAMP,
    order_delivered_customer_date   TIMESTAMP,
    order_estimated_delivery_date   TIMESTAMP
);

DROP TABLE IF EXISTS raw_order_items CASCADE;
CREATE TABLE raw_order_items (
    order_id            VARCHAR(50),
    order_item_id       INT,
    product_id          VARCHAR(50),
    seller_id           VARCHAR(50),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(10,2),
    freight_value       NUMERIC(10,2)
);

DROP TABLE IF EXISTS raw_products CASCADE;
CREATE TABLE raw_products (
    product_id                  VARCHAR(50) PRIMARY KEY,
    product_category_name       VARCHAR(100),
    product_name_length         INT,
    product_description_length  INT,
    product_photos_qty          INT,
    product_weight_g            INT,
    product_length_cm           INT,
    product_height_cm           INT,
    product_width_cm            INT
);

DROP TABLE IF EXISTS raw_customers CASCADE;
CREATE TABLE raw_customers (
    customer_id             VARCHAR(50) PRIMARY KEY,
    customer_unique_id      VARCHAR(50),
    customer_zip_code       VARCHAR(10),
    customer_city           VARCHAR(100),
    customer_state          VARCHAR(5)
);

DROP TABLE IF EXISTS raw_order_payments CASCADE;
CREATE TABLE raw_order_payments (
    order_id                VARCHAR(50),
    payment_sequential      INT,
    payment_type            VARCHAR(30),
    payment_installments    INT,
    payment_value           NUMERIC(10,2)
);

DROP TABLE IF EXISTS raw_order_reviews CASCADE;
CREATE TABLE raw_order_reviews (
    review_id               VARCHAR(50),
    order_id                VARCHAR(50),
    review_score            INT,
    review_comment_title    VARCHAR(255),
    review_comment_message  TEXT,
    review_creation_date    TIMESTAMP,
    review_answer_timestamp TIMESTAMP
);

DROP TABLE IF EXISTS raw_sellers CASCADE;
CREATE TABLE raw_sellers (
    seller_id           VARCHAR(50) PRIMARY KEY,
    seller_zip_code     VARCHAR(10),
    seller_city         VARCHAR(100),
    seller_state        VARCHAR(5)
);


-- ===============================================================================================
-- SECTION 2: SIMULATED AD CAMPAIGN TABLE
--            (generated by Python notebook generate_ad_data.py and verified by verify_ad_data.py)
-- ===============================================================================================

DROP TABLE IF EXISTS raw_ad_campaigns CASCADE;
CREATE TABLE raw_ad_campaigns (
    date                    DATE,
    campaign_id             VARCHAR(50),
    campaign_name           VARCHAR(100),
    channel                 VARCHAR(50),        -- Google Search, Meta Ads, Display, Retargeting
    product_category        VARCHAR(100),
    product_category_eng    VARCHAR(100),        -- English category name
    impressions             INT,
    clicks                  INT,
    ad_spend                NUMERIC(10,2),
    attributed_orders       INT,
    attributed_revenue      NUMERIC(10,2)
);


-- =============================================================================
-- SECTION 3: CLEANED / ANALYTICS LAYER
--            These views and tables power the Tableau dashboard + Python analysis
-- =============================================================================

-- -------------------------
-- 3a. Fact: Orders (cleaned)
-- -------------------------
DROP VIEW IF EXISTS fct_orders CASCADE;
CREATE VIEW fct_orders AS
SELECT
    o.order_id,
    o.customer_id,
    o.order_status,
    o.order_purchase_timestamp                          AS purchased_at,
    DATE_TRUNC('day',  o.order_purchase_timestamp)      AS purchase_date,
    DATE_TRUNC('week', o.order_purchase_timestamp)      AS purchase_week,
    DATE_TRUNC('month',o.order_purchase_timestamp)      AS purchase_month,
    EXTRACT(DOW FROM o.order_purchase_timestamp)        AS day_of_week,  -- 0=Sun
    EXTRACT(HOUR FROM o.order_purchase_timestamp)       AS purchase_hour,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,
    -- Delivery performance flag
    CASE
        WHEN o.order_delivered_customer_date <= o.order_estimated_delivery_date
        THEN 'On Time'
        ELSE 'Late'
    END                                                 AS delivery_status,
    -- Days to deliver
    EXTRACT(EPOCH FROM (
        o.order_delivered_customer_date - o.order_purchase_timestamp
    )) / 86400                                          AS days_to_deliver
FROM raw_orders o
WHERE o.order_status = 'delivered'      -- only completed orders for revenue analysis
  AND o.order_purchase_timestamp IS NOT NULL;


-- -------------------------
-- 3b. Fact: Order Revenue
-- -------------------------
DROP VIEW IF EXISTS fct_order_revenue CASCADE;
CREATE VIEW fct_order_revenue AS
SELECT
    oi.order_id,
    oi.order_item_id,
    oi.product_id,
    oi.seller_id,
    p.product_category_name                             AS product_category,
    oi.price,
    oi.freight_value,
    (oi.price + oi.freight_value)                       AS total_item_value,
    pay.payment_type,
    pay.payment_installments,
    pay.payment_value                                   AS total_payment
FROM raw_order_items oi
LEFT JOIN raw_products p
    ON oi.product_id = p.product_id
LEFT JOIN (
    -- Aggregate payments per order (some orders have multiple payment rows)
    SELECT order_id,
           MAX(payment_type)           AS payment_type,
           MAX(payment_installments)   AS payment_installments,
           SUM(payment_value)          AS payment_value
    FROM raw_order_payments
    GROUP BY order_id
) pay ON oi.order_id = pay.order_id;


-- -------------------------
-- 3c. Dim: Customers
-- -------------------------
DROP VIEW IF EXISTS dim_customers CASCADE;
CREATE VIEW dim_customers AS
SELECT
    customer_id,
    customer_unique_id,
    customer_city,
    customer_state,
    -- Region mapping for Brazil
    CASE customer_state
        WHEN 'SP' THEN 'Southeast'
        WHEN 'RJ' THEN 'Southeast'
        WHEN 'MG' THEN 'Southeast'
        WHEN 'ES' THEN 'Southeast'
        WHEN 'RS' THEN 'South'
        WHEN 'SC' THEN 'South'
        WHEN 'PR' THEN 'South'
        WHEN 'BA' THEN 'Northeast'
        WHEN 'CE' THEN 'Northeast'
        WHEN 'PE' THEN 'Northeast'
        WHEN 'DF' THEN 'Central-West'
        WHEN 'GO' THEN 'Central-West'
        WHEN 'AM' THEN 'North'
        WHEN 'PA' THEN 'North'
        ELSE 'Other'
    END AS region
FROM raw_customers;


-- -------------------------
-- 3d. Fact: Ad Campaigns (cleaned)
-- -------------------------
DROP VIEW IF EXISTS fct_ad_campaigns CASCADE;
CREATE VIEW fct_ad_campaigns AS
SELECT
    date                                                            AS campaign_date,
    DATE_TRUNC('week',  date::TIMESTAMP)                           AS campaign_week,
    DATE_TRUNC('month', date::TIMESTAMP)                           AS campaign_month,
    campaign_id,
    campaign_name,
    channel,
    product_category_eng                                            AS product_category,
    impressions,
    clicks,
    ad_spend,
    attributed_orders,
    attributed_revenue,
    -- Derived metrics
    ROUND(clicks::NUMERIC / NULLIF(impressions, 0) * 100, 4)                        AS ctr_pct,
    ROUND(attributed_orders::NUMERIC / NULLIF(clicks, 0) * 100, 4)                 AS cvr_pct,
    ROUND(attributed_revenue / NULLIF(ad_spend, 0), 4)                             AS roas,
    ROUND(ad_spend / NULLIF(clicks, 0), 4)                                          AS cpc,
    ROUND(ad_spend / NULLIF(attributed_orders, 0), 4)                              AS cpa,
    ROUND(attributed_revenue / NULLIF(attributed_orders, 0), 2)                    AS avg_order_value,
    ROUND((attributed_revenue - ad_spend) / NULLIF(ad_spend, 0) * 100, 2)          AS roi_pct
FROM raw_ad_campaigns
WHERE impressions > 0
  AND ad_spend > 0;


-- =============================================================================
-- INDEXES for query performance
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_orders_status    ON raw_orders(order_status);
CREATE INDEX IF NOT EXISTS idx_orders_date      ON raw_orders(order_purchase_timestamp);
CREATE INDEX IF NOT EXISTS idx_items_order      ON raw_order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_items_product    ON raw_order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_payments_order   ON raw_order_payments(order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_order    ON raw_order_reviews(order_id);
CREATE INDEX IF NOT EXISTS idx_ads_date         ON raw_ad_campaigns(date);
CREATE INDEX IF NOT EXISTS idx_ads_channel      ON raw_ad_campaigns(channel);
CREATE INDEX IF NOT EXISTS idx_ads_category     ON raw_ad_campaigns(product_category_eng);

-- =============================================================================
-- DONE. Run 02_funnel_analysis.sql next.
-- =============================================================================
